// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLtrocsd-H3_TOxZ3uHcuetlFvvWipc_0',
    appId: '1:1065553518843:android:5338eab697ff269df5505e',
    messagingSenderId: '1065553518843',
    projectId: 'somativaflutter',
    storageBucket: 'somativaflutter.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLtrocsd-H3_TOxZ3uHcuetlFvvWipc_0',
    appId: '1:1065553518843:web:198b9ac37c924707f5505e',
    messagingSenderId: '1065553518843',
    projectId: 'somativaflutter',
    authDomain: 'somativaflutter.firebaseapp.com',
    storageBucket: 'somativaflutter.firebasestorage.app',
    measurementId: 'G-04ZS2L3ED1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLtrocsd-H3_TOxZ3uHcuetlFvvWipc_0',
    appId: '1:1065553518843:android:5338eab697ff269df5505e',
    messagingSenderId: '1065553518843',
    projectId: 'somativaflutter',
    storageBucket: 'somativaflutter.firebasestorage.app',
    iosBundleId: 'com.example.exemploFirebase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLtrocsd-H3_TOxZ3uHcuetlFvvWipc_0',
    appId: '1:1065553518843:android:5338eab697ff269df5505e',
    messagingSenderId: '1065553518843',
    projectId: 'somativaflutter',
    storageBucket: 'somativaflutter.firebasestorage.app',
    iosBundleId: 'com.example.exemploFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLtrocsd-H3_TOxZ3uHcuetlFvvWipc_0',
    appId: '1:1065553518843:web:8b9da7109487949ef5505e',
    messagingSenderId: '1065553518843',
    projectId: 'somativaflutter',
    authDomain: 'somativaflutter.firebaseapp.com',
    storageBucket: 'somativaflutter.firebasestorage.app',
    measurementId: 'G-PXY4FR72SM',
  );

}